### ISSUE TITLE
pip install failure on Ubuntu Xenial

### ISSUE THREAD

**Issue by kblackstone81** [intra2net/guibot#1]
Installing the latest on Ubuntu 16.04 gives the following error:
root@5201c653f22d:/home/bot/autopy# pip install guibot
Collecting guibot
  Downloading https://files.pythonhosted.org/packages/c7/8e/998175b207247da4c346cc34f676862e3e36b691a9c9f0404dce6b5cc649/guibot-0.30.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kFUEv4/guibot/setup.py", line 10, in <module>
        with open(path.join(p, '../README.md')) as f:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-kFUEv4/guibot/../README.md'

However, installing 0.21.1 is successful.
pip install guibot==0.21.1

**Comment by pevogam** [comment]
Currently we only officially support Ubuntu 18.04 and above for the python 3 package since it contains the python 3 bindings for OpenCV. Xenial only offers python 2 bindings with a `python-opencv` package. We exclude the OpenCV dependence on some platforms but haven't tried building a Debian package for Xenial so far. Are you planning to use OpenCV in your use case?

**Comment by kblackstone81** [comment]
ah I see.  I shouldn't need OpenCV, just taking some screenshots of the app after various inputs and comparing it against the expected result.

**Comment by pevogam** [comment]
So unless python2 is not satisfactory for this purpose, I am not sure we can look into compatibility with Xenial, at least until next week or so.

**Comment by pevogam** [comment]
Hi again @kblackstone81, were you installing guibot for python 2 on Ubuntu 18.04? From your trace I can see that you ran "pip" instead of "pip3" and we the final guibot releases supporting python 2 are 0.2X.X. In particular, the 0.3X and any later releases will only support python 3. This is also the main difference in the 0.2 and 0.3 releases above.

In your invocation above, you downloaded a source distribution rather than a wheel (only python 3 wheel is available) and pip tried to build the package from this source bailing out because it is also the source distribution for python 3. If you confirm that you meant to run on python 2 (and should thus use a 0.2X release), I will close this issue.

**Comment by kblackstone81** [comment]
yeah, feel free to close the issue.
